{
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
    },
    "env": {
        "node": true,
    },
    "rules": {
        "brace-style": [2, "stroustrup", { "allowSingleLine": true }],
        "comma-dangle": [ 2, "always-multiline" ],
        "comma-style": 2,
        "consistent-this": 0,
        "curly": [ 2, "all" ],
        "dot-location": [ 2, "property"],
        "dot-notation": 2,
        "eol-last": 2,
        "eqeqeq": 2,
        "func-style": [2, "expression"],
        "guard-for-in": 2,
        "indent": [2, 4, { "SwitchCase": 1 }],
        "no-alert": 2,
        "no-caller": 2,
        "no-case-declarations": 2,
        "no-class-assign": 2,
        "no-const-assign": 2,
        "no-control-regex": 0,
        "no-dupe-class-members": 2,
        "no-labels": 2,
        "no-empty-pattern": 2,
        "no-eval": 2,
        "no-extend-native": 2,
        "no-extra-bind": 2,
        "no-fallthrough": 2,
        "no-floating-decimal": 2,
        "no-implicit-coercion": [2, {"boolean": false, "number": true, "string": true}],
        "no-implied-eval": 2,
        "no-iterator": 2,
        "no-loop-func": 2,
        "no-multi-spaces": 0,
        "no-multi-str": 2,
        "no-native-reassign": 2,
        "no-new-func": 2,
        "no-new-wrappers": 2,
        "no-octal": 2,
        "no-octal-escape": 2,
        "no-proto": 2,
        "no-redeclare": 2,
        "no-return-assign": 2,
        "no-script-url": 2,
        "no-self-compare": 2,
        "no-sequences": 2,
        "no-shadow": 2,
        "no-shadow-restricted-names": 2,
        "no-throw-literal": 2,
        "no-underscore-dangle": 0,
        "no-unexpected-multiline": 2,
        "no-unused-expressions": 2,
        "no-use-before-define": 2,
        "no-useless-call": 2,
        "no-useless-concat": 2,
        "no-var": 2,
        "no-void": 2,
        "no-warning-comments": [2, { "terms": ["fixme"], "location": "anywhere" }],
        "no-with": 2,
        "prefer-const": 2,
        "prefer-spread": 2,
        "prefer-template": 2,
        "quotes": [ 2, "double" ],
        "semi": 2,
        "keyword-spacing": 2,
        "wrap-iife": [2, "inside"],
    }
}
